# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

from waflib import Utils

top = '..'

def build(bld):
    unittests = bld.program(
        target = "../unit-tests",
        features = "cxx cxxprogram",
        source = bld.path.ant_glob(['**/*.cpp']),
        use = 'ndn-repo-objects',
        install_path = None,
        )
