# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    if bld.env['WITH_EXAMPLES']:
        for app in bld.path.ant_glob('*.cpp'):
            bld(features=['cxx', 'cxxprogram'],
                target='%s' % (str(app.change_ext('', '.cpp'))),
                source=app,
                use='NDN_CXX',
                includes="../src",
                install_path=None,
                )
