# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    for ex in bld.path.ant_glob('*.cpp'):
        name = ex.change_ext('').path_from(bld.path.get_bld())
        bld.program(name='example-%s' % name,
                    target=name,
                    source=[ex],
                    use='NDN_CXX',
                    includes='../src',
                    install_path=None)
